### ISSUE TITLE
Cannot change the Timezone and desc while creating the project

### ISSUE THREAD

**Issue by nbtri** [btnguyen2k/goapi.g8#1]
<img width="899" alt="Screen Shot 2019-11-22 at 4 04 46 PM" src="https://user-images.githubusercontent.com/1681110/69412883-54cdd680-0d42-11ea-9d60-4f0874f4bf2d.png">

**Comment by btnguyen2k** [comment]
This is issue of tool [btnguyen2k/go-giter8](https://github.com/btnguyen2k/go-giter8) not this template.
